name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  DRY_RUN: ${{ github.ref != 'refs/heads/main' }}
  OWNER: ${{ github.repository_owner }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - uses: sigstore/cosign-installer@ced07f21fb1da67979f539bbc6304c16c0677e76 # tag=v2.7.0

      - name: Docker registry login
        if: env.DRY_RUN == 'false'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ env.OWNER }} --password-stdin

      - name: Publish to docker.io
        uses: renovatebot/internal-tools@ce727ab40ccdba27634d298a3ac29eef4e26e32d # tag=v1.14.3
        with:
          command: docker-builder
          image-prefix: ${{ env.OWNER }}
          last-only: true
          major-minor: false
          dry-run: ${{ env.DRY_RUN }}

      - name: Publish to ghcr.io
        uses: renovatebot/internal-tools@ce727ab40ccdba27634d298a3ac29eef4e26e32d # tag=v1.14.3
        with:
          command: docker-builder
          image-prefix: ghcr.io/${{ env.OWNER }}
          last-only: true
          major-minor: false
          dry-run: ${{ env.DRY_RUN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Init
        run: ./bin/init.sh

      - uses: ncipollo/release-action@4c75f0f2e4ae5f3c807cf0904605408e319dcaac # tag=v1.11.1
        if: env.DRY_RUN == 'false'
        with:
          allowUpdates: true
          body: See https://github.com/containerbase/buildpack/releases/tag/${{ env.VERSION }} for more changes
          commit: ${{ github.sha }}
          name: ${{ env.VERSION }}
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
