name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  DRY_RUN: ${{ github.ref != 'refs/heads/main' }}
  OWNER: ${{ github.repository_owner }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - uses: sigstore/cosign-installer@116dc6872c0a067bcb78758f18955414cdbf918f # renovate: tag=v1.4.1

      - name: Docker registry login
        if: env.DRY_RUN == 'false'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ env.OWNER }} --password-stdin

      - name: Publish to docker.io
        uses: renovatebot/internal-tools@4d9e17a6613f0a82a98830e3424d35ece662122b # renovate: tag=v1.11.5
        with:
          command: docker-builder
          image-prefix: ${{ env.OWNER }}
          last-only: true
          major-minor: false
          dry-run: ${{ env.DRY_RUN }}

      - name: Publish to ghcr.io
        uses: renovatebot/internal-tools@4d9e17a6613f0a82a98830e3424d35ece662122b # renovate: tag=v1.11.5
        with:
          command: docker-builder
          image-prefix: ghcr.io/${{ env.OWNER }}
          last-only: true
          major-minor: false
          dry-run: ${{ env.DRY_RUN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Init
        run: ./bin/init.sh

      - uses: ncipollo/release-action@40bb172bd05f266cf9ba4ff965cb61e9ee5f6d01 # renovate: tag=v1.9.0
        if: env.DRY_RUN == 'false'
        with:
          allowUpdates: true
          body: See https://github.com/containerbase/buildpack/releases/tag/${{ env.VERSION }} for more changes
          commit: ${{ github.sha }}
          name: ${{ env.VERSION }}
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
